apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  # docker run -d --name nginx nginx
  - name: nginx
    image: nginx
  nodeselector:
    hardware: gpu  
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"